name: .NET CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
  

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  deploy: 

    runs-on: ubuntu-latest
    needs: test
    if: success() && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'Donkey.API/appsettings.json'
        env:
          ConnectionStrings.Default: ${{ secrets.DB_CONNECTION_STRING}}              
      - name: Build and push Docker to Heroku
        env:
          HEROKU_APP_NAME: dev-donkey-api
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          DOCKER_OPTIONS: "--no-cache"
        run: |
          cd ./Donkey.API
          heroku container:login
          heroku container:push web --context-path ../ --app ${HEROKU_APP_NAME}
          heroku container:release web --app ${HEROKU_APP_NAME}
